### ISSUE TITLE
Use whatthecommit.com/index.txt

### ISSUE THREAD

**Issue by adriangoransson** [linde12/whatthecommit-cli#1]
Completely unnecessary extracting the content of http://whatthecommit.com/ when you can curl http://whatthecommit.com/index.txt for clean output instead.

:D

**Comment by linde12** [comment]
3330f22fe250397f9b613525d7fd5a8568e91e6f

**Comment by linde12** [comment]
Closed by 3330f22fe250397f9b613525d7fd5a8568e91e6f
